const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const store={get:k=>JSON.parse(localStorage.getItem(`meu-lipedema-${k}`)||'[]'),set:(k,v)=>localStorage.setItem(`meu-lipedema-${k}`,JSON.stringify(v))};
const today=new Date().toISOString().slice(0,10),dateBR=v=>new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'});
const defaults=[['A','Pernas e glúteos','Força e estabilidade para membros inferiores'],['B','Superiores','Costas, braços, peito e ombros'],['C','Pernas leve e circulação','Movimento suave para ativar a circulação'],['D','Corpo inteiro','Um treino completo e equilibrado']].map(([id,name,description])=>({id,name,description,exercises:[]}));let activeRoutine=null;
function routines(){const saved=store.get('routines');if(!saved.length){store.set('routines',defaults);return defaults}return saved}function saveRoutines(v){store.set('routines',v)}
function setDates(){$$('input[name="date"]').forEach(i=>i.value=today);$('#today-label').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'}).replace(/^./,l=>l.toUpperCase())}
function showTab(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));if(id==='historico')renderHistory();if(id==='inicio')renderHome();if(id==='treino')renderTodayPicker();if(id==='meus-treinos')renderEditorPicker();window.scrollTo({top:0,behavior:'smooth'})}$$('.nav-link').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.go)));
function cards(target,click){target.innerHTML=routines().map(r=>`<button class="routine-card" data-routine="${r.id}"><b>Treino ${r.id}</b><h3>${r.name}</h3><p>${r.description}</p><p>${r.exercises.length} exercício${r.exercises.length===1?'':'s'} cadastrado${r.exercises.length===1?'':'s'}</p></button>`).join('');$$('[data-routine]',target).forEach(b=>b.onclick=()=>click(b.dataset.routine))}
function renderTodayPicker(){activeRoutine=null;$('#today-routine-picker').classList.remove('hidden');$('#active-workout').classList.add('hidden');cards($('#today-routine-picker'),startWorkout)}function renderEditorPicker(){activeRoutine=null;$('#routine-picker').classList.remove('hidden');$('#routine-editor').classList.add('hidden');cards($('#routine-picker'),openEditor)}
function dataFrom(target){return $$('.exercise-card',target).map(c=>Object.fromEntries($$('input',c).map(i=>[i.name,i.value]))).filter(x=>x.exercise)}
function card(data={},mode='edit'){const f=$('#exercise-template').content.cloneNode(true),c=$('.exercise-card',f),inputs=$$('input',f),edit=$('.edit-exercise',f),save=$('.save-exercise',f),remove=$('.remove-exercise',f);inputs.forEach(i=>i.value=data[i.name]||'');if(mode==='edit')inputs.forEach(i=>i.disabled=true);if(mode==='run'){$('.exercise-actions',f).style.display='none'}edit.onclick=()=>{inputs.forEach(i=>i.disabled=false);edit.textContent='Editando'};save.onclick=()=>{if(!inputs.find(i=>i.name==='exercise').value.trim()){alert('Informe o nome do exercício antes de salvar.');return}saveExercises();inputs.forEach(i=>i.disabled=true);edit.textContent='Editar';save.textContent='Salvo ✓'};remove.onclick=()=>{c.remove();saveExercises();renumberEditorExercises()};return f}
function renderExercises(target,items,mode){target.innerHTML='';items.forEach((x,i)=>{const f=card(x,mode);$('.exercise-number',f).textContent=`EXERCÍCIO ${i+1}`;target.append(f)});if(!items.length)target.innerHTML='<div class="history-empty">Este treino ainda não tem exercícios. Use “Adicionar exercício” para montar a rotina.</div>'}
function openEditor(id){activeRoutine=routines().find(r=>r.id===id);$('#routine-picker').classList.add('hidden');$('#routine-editor').classList.remove('hidden');$('#editor-routine-letter').textContent=`TREINO ${activeRoutine.id}`;$('#editor-routine-name').textContent=activeRoutine.name;renderExercises($('#routine-exercise-list'),activeRoutine.exercises,'edit')}
function saveExercises(){if(!activeRoutine)return;const list=routines(),routine=list.find(r=>r.id===activeRoutine.id);routine.exercises=dataFrom($('#routine-exercise-list'));saveRoutines(list);activeRoutine=routine}
function renumberEditorExercises(){$$('.exercise-number',$('#routine-exercise-list')).forEach((el,i)=>el.textContent=`EXERCÍCIO ${i+1}`)}
$('#add-exercise').onclick=()=>{const list=$('#routine-exercise-list');if($('.history-empty',list))list.innerHTML='';const f=card({},'new');$('.exercise-number',f).textContent=`EXERCÍCIO ${list.children.length+1}`;list.append(f)};$('#back-to-routines').onclick=()=>{saveExercises();renderEditorPicker()};
function startWorkout(id){activeRoutine=routines().find(r=>r.id===id);$('#today-routine-picker').classList.add('hidden');$('#active-workout').classList.remove('hidden');$('#active-routine-letter').textContent=`TREINO ${activeRoutine.id}`;$('#active-routine-name').textContent=activeRoutine.name;renderExercises($('#exercise-list'),activeRoutine.exercises,'run');$('#workout-status').textContent=''}$('#change-routine').onclick=renderTodayPicker;
$('#finish-workout').onclick=()=>{const exercises=dataFrom($('#exercise-list'));if(!exercises.length){$('#workout-status').textContent='Este treino não possui exercícios para concluir.';return}const w=store.get('workouts');w.unshift({id:Date.now(),date:today,routine:`Treino ${activeRoutine.id} – ${activeRoutine.name}`,exercises});store.set('workouts',w);$('#workout-status').textContent='Treino salvo e concluído!';renderHome()};
$('#measurements-form').onsubmit=e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.target)),l=store.get('measurements');l.unshift({id:Date.now(),...x});store.set('measurements',l);e.target.reset();e.target.date.value=today;alert('Medidas salvas com carinho.')};function range(id){const i=$(`#${id}`);i.oninput=()=> $(`#${id}-value`).textContent=i.value}range('pain');range('swelling');
$('#symptoms-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),x=Object.fromEntries(f);x.legHeaviness=f.get('legHeaviness')==='on';x.compression=f.get('compression')==='on';const l=store.get('symptoms');l.unshift({id:Date.now(),...x});store.set('symptoms',l);e.target.reset();e.target.date.value=today;$('#pain-value').textContent=$('#swelling-value').textContent='0';alert('Check-in salvo. Obrigada por se escutar hoje.');renderHome()};
function renderHome(){const w=store.get('workouts'),s=store.get('symptoms'),m=store.get('measurements'),start=new Date();start.setDate(start.getDate()-start.getDay());start.setHours(0,0,0,0);const inWeek=x=>new Date(`${x.date}T12:00:00`)>=start;$('#stat-workouts').textContent=w.filter(inWeek).length;const weight=[...s,...m].filter(x=>x.weight).sort((a,b)=>b.id-a.id)[0];$('#stat-weight').textContent=weight?`${String(weight.weight).replace('.',',')} kg`:'—';const ss=s.filter(inWeek);$('#stat-pain').textContent=ss.length?(ss.reduce((a,x)=>a+Number(x.pain),0)/ss.length).toFixed(1).replace('.',','):'—';const tw=w.find(x=>x.date===today);$('#home-workout').innerHTML=tw?`<strong>${tw.routine||'Treino concluído'} ✓</strong><br><span>${tw.exercises.map(e=>e.exercise).join(' · ')}</span>`:'Nenhum treino concluído hoje.<button class="inline-action" data-go="treino">Escolher treino</button>';const ts=s.find(x=>x.date===today);$('#home-checkin').innerHTML=ts?`<strong>Dor ${ts.pain}/10 · Inchaço ${ts.swelling}/10</strong><br><span>${ts.legHeaviness?'Com sensação de peso nas pernas':'Sem sensação de peso registrada'}</span>`:'Ainda não há sintomas registrados hoje.<button class="inline-action" data-go="peso">Fazer check-in</button>';$$('#inicio [data-go]').forEach(b=>b.onclick=()=>showTab(b.dataset.go))}
let filter='all';$$('.history-filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.history-filter').forEach(x=>x.classList.toggle('active',x===b));renderHistory()});function renderHistory(){let items=[...store.get('workouts').map(x=>({...x,type:'workout',title:x.routine||'Treino concluído',detail:`${x.exercises.length} exercício${x.exercises.length===1?'':'s'} · ${x.exercises.map(e=>`${e.exercise}${e.load?` (${e.load} kg)`:''}`).join(', ')}`})),...store.get('measurements').map(x=>({...x,type:'measurement',title:'Medidas registradas',detail:[x.weight&&`${x.weight} kg`,x.waist&&`cintura ${x.waist} cm`,x.hip&&`quadril ${x.hip} cm`].filter(Boolean).join(' · ')||'Registro corporal'})),...store.get('symptoms').map(x=>({...x,type:'symptom',title:'Check-in de sintomas',detail:`Dor ${x.pain}/10 · Inchaço ${x.swelling}/10${x.compression?' · Meia compressiva':''}`}))].sort((a,b)=>b.id-a.id);if(filter!=='all')items=items.filter(x=>x.type===filter);const tags={workout:'TREINO',measurement:'MEDIDAS',symptom:'SINTOMAS'};$('#history-list').innerHTML=items.length?items.map(x=>`<article class="history-item"><div><h3>${x.title}</h3><p>${dateBR(x.date)} · ${x.detail}</p></div><span class="tag">${tags[x.type]}</span></article>`).join(''):'<div class="history-empty">Ainda não há registros aqui. Quando você salvar algo, ele aparecerá neste espaço.</div>'}
setDates();routines();renderHome();renderTodayPicker();
